### ISSUE TITLE
Unable to add middleware to any PAGE request

### ISSUE THREAD

**Issue by ziedHamdi** [htunnicliff/next-api-middleware#63]
**Is your feature request related to a problem? Please describe.**
I installed the lib to add a threadLocal like behavior to any of my pages : storing request scoped variables to use throughout the request processing. I needed the lib to init the variables at page request and clean them after the page is processed. I cannot find any way to use the lib for any page (like a app.all() in expressjs) 
**Describe the solution you'd like**
I would like to apply the middleware to any page rendering
**Describe alternatives you've considered**
I can use nextjs middleware rewrites 
**Additional context**
Also, note it is not easy from the docs to understand you only handle API requests, I lost some time before I realized it

**Comment by htunnicliff** [comment]
Hi @ziedHamdi – `next-api-middleware` is a library specifically written for use with Next.js API routes. It is not configured for use with Next.js pages. 

Since the time that this library was created, the Next.js team has created a different kind of [Middleware solution](https://nextjs.org/docs/advanced-features/middleware) that could be used with pages. I would suggest taking a look at that to see if it can meet your needs!

Per your comment about the docs:

> Also, note it is not easy from the docs to understand you only handle API requests, I lost some time before I realized it.

Do you have any suggestions on how I could make it clearer that this library is only for API routes?

**Comment by ziedHamdi** [comment]
Ok thanks for the link Hunter
